FROM ubuntu:latest

RUN yes | unminimize
RUN apt-get upgrade
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN pip3 install py-solc-x
RUN pip3 install web3

COPY Projects /projects