FROM ubuntu:latest

RUN yes | unminimize
RUN apt-get upgrade
RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_16.x && apt-get install -y nodejs && apt-get install -y npm
RUN npm install --global yarn
RUN yarn global add ganache-cli

CMD ganache-cli --deterministic