dotenv: .env

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

wallets:
  from_key: ${PRIVATE_KEY}

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

networks:
  rinkeby:
    eth_usd_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'